import UIKit
import PlaygroundSupport

let digitRecognitionVC: DigitRecognitionResultViewController = DigitRecognitionResultViewController.instantiateFromStoryboard()
PlaygroundPage.current.liveView = digitRecognitionVC
