import UIKit
import PlaygroundSupport

let objectRecognitionVC: ObjectRecognitionResultViewController = ObjectRecognitionResultViewController.instantiateFromStoryboard()
PlaygroundPage.current.liveView = objectRecognitionVC

